### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by Hardik7538** [ArkeologeN/node-linkedin#85]
return callback(err, typeof body === 'string' ? JSON.parse(body) : body);

**Comment by petermirmo** [comment]
I have the same issue. When trying to share to a page I get this error: 


 C:\Users\peter\Desktop\NextProjects\ghostit-dev\node_modules\node-linkedin\lib\inherits.js:52
[0]                     return callback(err, typeof body === 'string' ? JSON.parse(body) : body);
[0]                            ^
[0]
[0] TypeError: callback is not a function
[0]     at Request._callback (C:\Users\peter\Desktop\NextProjects\ghostit-dev\node_modules\node-linkedin\lib\inherits.js:52:28)
[0]     at Request.self.callback (C:\Users\peter\Desktop\NextProjects\ghostit-dev\node_modules\request\request.js:186:22)
[0]     at Request.emit (events.js:160:13)
[0]     at Request.<anonymous> (C:\Users\peter\Desktop\NextProjects\ghostit-dev\node_modules\request\request.js:1163:10)
[0]     at Request.emit (events.js:160:13)
[0]     at IncomingMessage.<anonymous> (C:\Users\peter\Desktop\NextProjects\ghostit-dev\node_modules\request\request.js:1085:12)
[0]     at Object.onceWrapper (events.js:255:19)
[0]     at IncomingMessage.emit (events.js:165:20)
[0]     at endReadableNT (_stream_readable.js:1101:12)
[0]     at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by petermirmo** [comment]
`var LI = Linkedin.init(account.accessToken);
                var linkedinPost = {};
                var linkedinLink = {};
                if (post.content !== "") {
                    linkedinPost.comment = post.content;
                }
                if (post.link !== "") {
                    linkedinLink["submitted-url"] = post.link;
                    linkedinPost.content = linkedinLink;
                }
                if (post.linkImage !== "" && post.link !== "") {
                    linkedinLink["submitted-image-url"] = post.linkImage;
                    linkedinPost.content = linkedinLink;
                }
                if (post.image) {
                    linkedinLink["submitted-image-url"] = post.image[0];
                    linkedinPost.content = linkedinLink;
                }
                linkedinPost.visibility = { code: "anyone" };
                return;
                LI.people.share(account.socialID, linkedinPost, function(
                    results
                ) {
                    console.log(results);
                    if (!results.updateKey) {
                        savePostError(post._id, results);
                    } else {
                        savePostSuccessfully(post._id, results.updateKey);
                    }
                });
            }`

**Comment by sullivandavid42** [comment]
Hello. Thanks for providing more info about your code, or close the issue.
Your problem is certainly due to a specific JS error and not frmo the node-linkedin API itself
