### ISSUE TITLE
SyntaxError: Unexpected token ... in JSON (body) response

### ISSUE THREAD

**Issue by aleCeres** [ArkeologeN/node-linkedin#86]
If `body` is not a JSON there is an error in
node-linkedin/lib/inherits.js:52

as you can see below:

```
request(parameters, function(err, response, body) {
    return callback(err, typeof body === 'string' ? JSON.parse(body) : body);
});
```

SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at Request._callback (/.../node_modules/node-linkedin/lib/inherits.js:52:74)
at Request.self.callback (/.../node_modules/request/request.js:186:22)

**Comment by Contributorseven** [comment]
What your exited about

**Comment by Contributorseven** [comment]
What is the real problem here?

**Comment by aleCeres** [comment]
I suppose that body is not a valid JSON.

**Comment by Contributorseven** [comment]
Stop the nonsense the total supply of 78042956829 tokens belong to Raymond j braydi to keep serving my platform it’s not for sale or to trade and not to be donated to digitalbazaar.com or hello@interchainventires.com ...
Now you all need to understand When faced a mountain I will not quit ! I will keep on striving until i clime over.fined a pass through,tunnel underneath - or simply stay and turn the mountain into a gold mine,with God help.
I want to restructure the hole operation keeping my Facebook team and the team manager safe and respected new guidelines  that prohibits any future fraud and miss conducts new serious respectful players from linked-in and tweeter can be more assets and I will keep the final decision to my Facebook 2 team manager ...

Thanks

Remo

**Comment by aleCeres** [comment]
Thank you man,
I dont like mountain
Thanks in advance

**Comment by rgglenn150** [comment]
> Thank you man,
> I dont like mountain
> Thanks in advance

Is it working now? how did you fixed it? I'm having the same problem.
