### ISSUE TITLE
invalid_request: A required parameter "code" is missing

### ISSUE THREAD

**Issue by fabianmedina09** [ArkeologeN/node-linkedin#92]
HI, this issue appears when it comes to adding the permission level "r_fullprofile" to the scope array.

{ invalid_request: A required parameter "code" is missing
    at Request._callback (D:\DATOS\DESKTOP\fmedinacv\fmedinaback\node_modules\node-linkedin\lib\auth.js:98:27)
    at Request.self.callback (D:\DATOS\DESKTOP\fmedinacv\fmedinaback\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\DATOS\DESKTOP\fmedinacv\fmedinaback\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\DATOS\DESKTOP\fmedinacv\fmedinaback\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20) name: 'invalid_request' }

How can i solve this?

In my linkedin app I only have this permission: (How can others be added?)
['r_basicprofile', 'r_liteprofile', 'r_emailaddress', 'w_share', 'rw_company_admin', 'w_member_social']

or there is some other way in which you can get all the profile information

**Comment by captainjackrana** [comment]
@fabianmedina09 do you still have the `r_basicprofile` permission in your app? If yes, then how did you get access to it, since Linkedin has revoked that access on most apps now
